#!/bin/sh
[ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ] || exit 0
[ -f /etc/init.d/adguardhome ] || exit 0
[ -f /etc/adguardhome/adguardhome.yaml ] || exit 0
[ -f /var/run/adguardhome-filters-initialized ] && exit 0

(sleep 20; /etc/init.d/adguardhome restart 2>/dev/null; touch /var/run/adguardhome-filters-initialized) &
